# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewCloneCoding1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewCloneCoding1
    pod 'SnapKit'
    pod 'Then'
    pod 'Alamofire'

end
